export const ENDBOSS_IMAGES = {
    idle: [
        'img/enemys/Boss/Idle/skeleton-Idle_0.png',
        'img/enemys/Boss/Idle/skeleton-Idle_1.png',
        'img/enemys/Boss/Idle/skeleton-Idle_2.png',
        'img/enemys/Boss/Idle/skeleton-Idle_3.png',
        'img/enemys/Boss/Idle/skeleton-Idle_4.png',
        'img/enemys/Boss/Idle/skeleton-Idle_5.png',
        'img/enemys/Boss/Idle/skeleton-Idle_6.png',
        'img/enemys/Boss/Idle/skeleton-Idle_7.png',
        'img/enemys/Boss/Idle/skeleton-Idle_8.png',
        'img/enemys/Boss/Idle/skeleton-Idle_9.png',
        'img/enemys/Boss/Idle/skeleton-Idle_10.png',
        'img/enemys/Boss/Idle/skeleton-Idle_11.png',
        'img/enemys/Boss/Idle/skeleton-Idle_12.png',
        'img/enemys/Boss/Idle/skeleton-Idle_13.png',
        'img/enemys/Boss/Idle/skeleton-Idle_14.png',
        'img/enemys/Boss/Idle/skeleton-Idle_15.png',
        'img/enemys/Boss/Idle/skeleton-Idle_16.png',
        'img/enemys/Boss/Idle/skeleton-Idle_17.png',
    ],
    walking: [
        'img/enemys/Boss/Walk/skeleton-Walk_0.png',
        'img/enemys/Boss/Walk/skeleton-Walk_1.png',
        'img/enemys/Boss/Walk/skeleton-Walk_2.png',
        'img/enemys/Boss/Walk/skeleton-Walk_3.png',
        'img/enemys/Boss/Walk/skeleton-Walk_4.png',
        'img/enemys/Boss/Walk/skeleton-Walk_5.png',
        'img/enemys/Boss/Walk/skeleton-Walk_6.png',
        'img/enemys/Boss/Walk/skeleton-Walk_7.png',
        'img/enemys/Boss/Walk/skeleton-Walk_8.png',
        'img/enemys/Boss/Walk/skeleton-Walk_9.png',
        'img/enemys/Boss/Walk/skeleton-Walk_10.png',
        'img/enemys/Boss/Walk/skeleton-Walk_11.png',
        'img/enemys/Boss/Walk/skeleton-Walk_12.png',
        'img/enemys/Boss/Walk/skeleton-Walk_13.png',
        'img/enemys/Boss/Walk/skeleton-Walk_14.png',
        'img/enemys/Boss/Walk/skeleton-Walk_15.png',
        'img/enemys/Boss/Walk/skeleton-Walk_16.png',
        'img/enemys/Boss/Walk/skeleton-Walk_17.png'
    ],
    attacking: [
        'img/enemys/Boss/Attack/skeleton-Attack_0.png',
        'img/enemys/Boss/Attack/skeleton-Attack_1.png',
        'img/enemys/Boss/Attack/skeleton-Attack_2.png',
        'img/enemys/Boss/Attack/skeleton-Attack_3.png',
        'img/enemys/Boss/Attack/skeleton-Attack_4.png',
        'img/enemys/Boss/Attack/skeleton-Attack_5.png',
        'img/enemys/Boss/Attack/skeleton-Attack_6.png',
        'img/enemys/Boss/Attack/skeleton-Attack_7.png',
        'img/enemys/Boss/Attack/skeleton-Attack_8.png',
        'img/enemys/Boss/Attack/skeleton-Attack_9.png',
        'img/enemys/Boss/Attack/skeleton-Attack_10.png',
        'img/enemys/Boss/Attack/skeleton-Attack_11.png',
        'img/enemys/Boss/Attack/skeleton-Attack_12.png',
        'img/enemys/Boss/Attack/skeleton-Attack_13.png',
        'img/enemys/Boss/Attack/skeleton-Attack_14.png',
        'img/enemys/Boss/Attack/skeleton-Attack_15.png',
        'img/enemys/Boss/Attack/skeleton-Attack_16.png',
        'img/enemys/Boss/Attack/skeleton-Attack_17.png',
        'img/enemys/Boss/Attack/skeleton-Attack_18.png',
        'img/enemys/Boss/Attack/skeleton-Attack_19.png',
        'img/enemys/Boss/Attack/skeleton-Attack_20.png',
        'img/enemys/Boss/Attack/skeleton-Attack_21.png'
    ],
    death: [
        'img/enemys/Death Sprite/skeleton-animation_0.png',
        'img/enemys/Death Sprite/skeleton-animation_1.png',
        'img/enemys/Death Sprite/skeleton-animation_2.png',
        'img/enemys/Death Sprite/skeleton-animation_3.png',
        'img/enemys/Death Sprite/skeleton-animation_4.png',
        'img/enemys/Death Sprite/skeleton-animation_5.png',
        'img/enemys/Death Sprite/skeleton-animation_6.png',
        'img/enemys/Death Sprite/skeleton-animation_7.png',
        'img/enemys/Death Sprite/skeleton-animation_8.png',
        'img/enemys/Death Sprite/skeleton-animation_9.png'
    ]
};